# rTnTJump criado e desenvolvido por ReFlexoo.
# Version:
# 1.0

#Em caso de problemas acesse: https://discord.gg/eehY3dH5XU ou https://discord.gg/47j272usWF

options:

	Upwards: 2.0
	Forwards: 3.0
	Region: 5

on explosion:
	cancel event
	create a fake explosion at event-location
	loop all entities in radius {@Region} of event-location:
		push the loop-entity upwards at speed {@Upwards}
		push the loop-entity forwards at speed {@Forwards}